#!/usr/bin/env python
# encoding: utf-8
#
# Simple Base 64 encoder/decoder.
# You might want to install in into /usr/bin or something in your PATH.
#
# Author: Rasmus Andersson <http://hunch.se/>
# License: Public Domain
#
import sys,base64
def usage():
  sys.stderr.write("usage: %s encode|decode [FILE]\n" % sys.argv[0]);
  sys.stderr.write("Encodes, or decodes base 64 encoded, data. If FILE is not specified, reads from stdin.\n");
  exit(1)
if len(sys.argv) < 2 or len(sys.argv[1]) < 3:
  usage()
inf = sys.stdin
if len(sys.argv) > 2:
  inf = open(sys.argv[2])
try:
  if sys.argv[1][:3] == 'dec':
    base64.decode(inf, sys.stdout)
  elif sys.argv[1][:3] == 'enc':
    base64.encode(inf, sys.stdout)
  else:
    sys.stderr.write("Unknown direction '%s'\n" % sys.argv[1])
    usage()
finally:
  try: inf.close()
  except: pass
